// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27ii57Idi9XZS9UqqKGX8Ef4PtwFBF40',
    appId: '1:779487278709:android:0d6ea2727413afec24aa3c',
    messagingSenderId: '779487278709',
    projectId: 'aptm-e363c',
    databaseURL: 'https://aptm-e363c-default-rtdb.firebaseio.com',
    storageBucket: 'aptm-e363c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaPJPiNp0VdmB-8tWBswjMbeHZrQmBMA',
    appId: '1:779487278709:ios:d5d9b9ae85459ab524aa3c',
    messagingSenderId: '779487278709',
    projectId: 'aptm-e363c',
    databaseURL: 'https://aptm-e363c-default-rtdb.firebaseio.com',
    storageBucket: 'aptm-e363c.appspot.com',
    iosClientId: '779487278709-ndbc03g9euvsrk6vq13570jpg0uffl4l.apps.googleusercontent.com',
    iosBundleId: 'com.aptm.ethicaldigit',
  );
}
